name: Build

on:
  push:
    branches:
      - master	

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      run: git clone --recurse-submodules https://github.com/jiowchern/Regulus.Samples.git    
    - name: Build with dotnet
      run: dotnet build --configuration Release ./Regulus.Samples/Regulus.Samples.sln
    - name: Test
      run: dotnet test ./Regulus.Samples
    
