name: Build

on:
  push:
    branches:
      - master	

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0        
    - name: Build with dotnet
      run: dotnet build --configuration Release
