name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest    

    steps:       
      - name: Clone
        shell: bash
        run : git clone --recurse-submodules -j8 https://github.com/jiowchern/Regulus.Samples.git
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Release
          
          
