name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:      
        name:  regulus.sampels.chat1.server
        # The login username for the registry
        username: jiowchern
        # The login password for the registry
        password: 3e01aa54da75ab697c6ee1486802fb04a0afcf56
        # Use registry for pushing to a custom registry
        registry: docker.pkg.github.com  
        # Use snapshot to push an additional image
        #snapshot: # optional
        # Use dockerfile when you would like to explicitly build a Dockerfile
        dockerfile: ./Regulus.Samples/Chat1/Regulus.Sampels.Chat1.Server
        # Use workdir when you would like to change the directory for building
        #workdir: # optional
        # Use buildargs when you want to pass a list of environment variables as build-args
        #buildargs: # optional
        # Use cache when you have big images, that you would only like to build partially
        #cache: # optional
        # Use tag_names when you want to push tags/release by their git name
        tag_names: regulus.sampels.chat1.server # optional
        
        
